version: '3'

services:
  app:
    image: lqtech/llm-web-backend
    container_name: llm_app
    network_mode: host
    environment:
      # define app server port.
      - APP_PORT=8200
      
      # define admin server port.
      # - ADMIN_PORT=8001
      
      # define server host, 0.0.0.0 for expose service.
      - HOST=0.0.0.0

      # define database file path inside container.
      - DATA_FILE_PATH=/var/llm-main.db

      # enable https? default enable.
      # - HTTPS_ENABLE=1

      # https key file path.
      # - SSL_KEYFILE=secrets/server.key

      # https cert file path.
      # - SSL_CERTFILE=secrets/server.crt

      # Session expires time in seconds.
      # - AUTH_EXPIRES=3600

      # Chat word black list file path.
      # - CAHT_CONFIG_PATH=/etc/llm/blacklist.conf

      # Sensitive content filter mode [disable|block|replace]
      # disable: disable all filter.
      # block: block any content which include sensitive words.
      # replace: replace sensitive words by its replacement.
      # - CHAT_BLACKLIST_MODE=block
 
    volumes:
      - /var/llm/:/var/:rw