version: '3.0'

services:
  app:
    image: lingqi/llm
    container_name: llm_app
    network_mode: host
    environment:
      # define app server port.
      # - APP_PORT=8000
      
      # define admin server port.
      # - ADMIN_PORT=8001
      
      # define server host, 0.0.0.0 for expose service.
      - HOST=0.0.0.0

      # define database file path inside container.
      - DATA_FILE_PATH=/var/data.db
    restart_policy:
        condition: on-failure
    volumes:
      - /var/:/var/:rw